name: Docker

on:
  pull_request:
    branches:
      - docker
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: docker build . --file Dockerfile --tag github-actions-demo:$GITHUB_SHA
